name: Code Review

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-comment:
    runs-on: ubuntu-latest
    environment: OpenAI
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install openai requests
    - name: Generate comment
      id: comment
      env:
        OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}'
      run: |
        PR_BRANCH=${{ github.event.pull_request.head.sha }}
        BASE_BRANCH=${{ github.event.pull_request.base.sha }}
        diff_content=$(git diff --no-prefix $BASE_BRANCH $PR_BRANCH)
        output=$(PATCH_CONTENT=$diff_content python .github/workflows/generate_comment.py)
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "OPEN_AI_COMMENT=$output" >> $GITHUB_OUTPUT
    - name: Post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ${{ steps.comment.outputs.OPEN_AI_COMMENT }}
