name: Code Review

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-comment:
    runs-on: ubuntu-latest
    environment: OpenAI
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get PR patch content
      id: get-pr-patch
      run: |
        PR_BRANCH=${{ github.event.pull_request.head.ref }}
        BASE_BRANCH=${{ github.event.pull_request.base.ref }}
        content=$(git diff --no-prefix $BASE_BRANCH $PR_BRANCH)
        echo "PATCH_CONTENT=content" >> $GITHUB_OUTPUT
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install openai requests
    - name: Generate comment
      id: comment
      env:
        OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}'
        PATCH_CONTENT: ${{ steps.get-pr-patch.outputs.PATCH_CONTENT }}
      run: |
        output=$(python .github/workflows/generate_comment.py)
        echo "OPEN_AI_COMMENT=$output" >> $GITHUB_OUTPUT
    - name: Post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: unsplash/comment-on-pr@v1.3.0
      with:
        msg: ${{ steps.comment.outputs.OPEN_AI_COMMENT }}
