name: Code Review

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-comment:
    runs-on: ubuntu-latest
    environment: OpenAI
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install openai requests
    - name: Generate comment
      id: comment
      env:
        OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}'
        PR_CONTENT: ${{ github.event.pull_request.body }}
      run: |
        output=$(python .github/workflows/generate_comment.py )
        echo "::set-output name=comment::$output"
    - name: Post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: unsplash/comment-on-pr@v1.3.0
      with:
        msg: ${{ steps.comment.outputs.comment }}
