name: Code Review

on:
  pull_request:
    types: [review_requested]

jobs:
  generate-comment:
    runs-on: ubuntu-latest
    if: github.event.requested_reviewer.login == 'github-actions[bot]'
    environment: OpenAI
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install openai PyGithub
    - name: Review changes
      env:
        OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}'
        OPENAI_API_TYPE: '${{ vars.OPENAI_API_TYPE }}'
        OPENAI_API_ENDPOINT: '${{ secrets.OPENAI_API_ENDPOINT }}'
        OPENAI_API_VERSION: '${{ vars.OPENAI_API_VERSION }}'
        AZURE_MODEL: '${{ vars.AZURE_MODEL }}'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{github.event.number}}
      run: python .github/workflows/review_pr.py
